/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.areacalculate;

/**
 *
 * @author solomon
 */
public class Area_calculate extends javax.swing.JFrame {

    /**
     * Creates new form Area_calculate
     */
    public Area_calculate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setBackground(new java.awt.Color(255, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acres", "Square meters", "Square feet", "Square inches", "Ares", "Hectares" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 102, 102));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox2.setBackground(new java.awt.Color(255, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acres", "Square meters", "Square feet", "Square inches", "Ares", "Hectares" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(255, 102, 102));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 204));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 255, 204));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("CALCULATING AREA");

        jLabel2.setText("Select:");

        jLabel3.setText("Select:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                    .addComponent(jButton3))
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    double num = Double.parseDouble(jTextField1.getText());
    if(jComboBox1.getSelectedItem().toString()== "Acres" && jComboBox2.getSelectedItem().toString()== "Square meters"){
        double result = num*4047;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Acres"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num*43560;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Acres"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*6.273e+6;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Acres"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num*40.469;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Acres"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/2.471;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num/4047;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num*10.764;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*1550;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num/100;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square meters"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/10000;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num/43560;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Square meters"){
        double result = num/10.764;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*144;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num/1076;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square feet"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/107600;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num/6.273e+6;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Square meters"){
        double result = num/1550;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num/144;
        jTextField2.setText(result+"");
        }
           
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num/155000;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Square inches"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/1.55e+7;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num*1076;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Square meters"){
        double result = num*100;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num*1076;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*155000;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Ares"&&jComboBox2.getSelectedItem().toString() == "Hectares"){
        double result = num/100;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Acres"){
        double result = num*2.71;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Square meters"){
        double result = num*10000;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Square feet"){
        double result = num*107600;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Square inches"){
        double result = num*1.55e+7;
        jTextField2.setText(result+"");
        }
        if(jComboBox1.getSelectedItem().toString() == "Hectares"&&jComboBox2.getSelectedItem().toString() == "Ares"){
        double result = num*100;
        jTextField2.setText(result+"");
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    System.exit(0);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Area_calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Area_calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Area_calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Area_calculate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Area_calculate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
